# Generated by Django 5.1.7 on 2025-03-16 14:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите имя автора', max_length=150, verbose_name='Имя автора')),
                ('bio', models.TextField(blank=True, help_text='Краткая биография автора(не обязательно)', max_length=3000, null=True, verbose_name='Краткая биография автора')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите название категории', max_length=150, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите название издателя', max_length=150, verbose_name='Название издателя')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Введите название книги', max_length=100, verbose_name='Название книги')),
                ('description', models.TextField(help_text='Описание книги', max_length=3000, verbose_name='Описание книги')),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2100)], verbose_name='Год выпуска')),
                ('author', models.ForeignKey(help_text='Выберите автора книги', on_delete=django.db.models.deletion.CASCADE, related_name='authored_books', to='main.author', verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='BookOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Описание объявления', max_length=3000, verbose_name='Описание объявления')),
                ('language', models.CharField(choices=[('en', 'Английский'), ('rus', 'Русский')], max_length=20, verbose_name='Язык')),
                ('edition_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2100)], verbose_name='Год издания книги')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания объявления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения объявления')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book', verbose_name='Книга')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(help_text='Выберите категории, к которым относится книга', related_name='categorized_books', through='main.BookCategory', to='main.category', verbose_name='Категории'),
        ),
        migrations.CreateModel(
            name='MainPageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('popular', 'Популярная'), ('new', 'Новая'), ('featured', 'Избранная')], max_length=20, verbose_name='Тип книги')),
                ('book_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bookoffer', verbose_name='Объявление')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, help_text='Выберите издателя книги', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.publisher', verbose_name='Издатель'),
        ),
    ]
