# Generated by Django 5.1.7 on 2025-03-16 15:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='Описание книги', max_length=3000, null=True, verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, help_text='Выберите издателя книги', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_books', to='main.publisher', verbose_name='Издатель'),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2100)], verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='bookoffer',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_offers', to='main.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='mainpagelist',
            name='book_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_page_lists', to='main.bookoffer', verbose_name='Объявление'),
        ),
    ]
