# Generated by Django 4.2.9 on 2025-04-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookoffer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус объявления'),
        ),
    ]
