# Generated by Django 5.1.7 on 2025-03-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_book_description_alter_book_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='png',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/', verbose_name='Фото категории'),
        ),
    ]
