# Generated by Django 5.1.7 on 2025-03-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_png'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='png',
            new_name='img',
        ),
    ]
