# Generated by Django 4.2.9 on 2025-04-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bookoffer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookoffer',
            name='is_active',
            field=models.TextField(choices=[('Active', 'Активное'), ('Completed', 'Завершенное')], default=True, verbose_name='Статус объявления'),
        ),
    ]
