# Generated by Django 3.2.16 on 2025-03-25 16:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите имя автора', max_length=150, verbose_name='Имя')),
                ('bio', models.TextField(blank=True, help_text='Краткая биография автора(не обязательно)', max_length=3000, null=True, verbose_name='Краткая биография')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Введите название книги', max_length=100, verbose_name='Название книги')),
                ('img', models.ImageField(blank=True, default='book/default_book/default.png', upload_to='book/default_book/', verbose_name='Фото')),
                ('language', models.CharField(choices=[('en', 'Английский'), ('rus', 'Русский')], max_length=20, verbose_name='Язык')),
                ('description', models.TextField(blank=True, help_text='Описание книги', max_length=3000, null=True, verbose_name='Описание книги')),
                ('release_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)], verbose_name='Год выпуска')),
                ('author', models.ForeignKey(help_text='Выберите автора книги', on_delete=django.db.models.deletion.CASCADE, related_name='authored_books', to='book.author', verbose_name='Автор')),
                ('category', models.ManyToManyField(help_text='Выберите категории, к которым относится книга', related_name='categorized_books', to='category.Category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите название издателя', max_length=150, verbose_name='Название издателя')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book/default_book/', verbose_name='Изображение')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='book.book', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, help_text='Выберите издателя книги', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_books', to='book.publisher', verbose_name='Издатель'),
        ),
    ]
