# Generated by Django 5.1.7 on 2025-03-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Английский', 'en'), ('Русский', 'ru')], max_length=20, verbose_name='Язык'),
        ),
    ]
