# Generated by Django 4.2.9 on 2025-04-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bookoffer_is_active'),
        ('user', '0003_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('user', 'offer')},
        ),
    ]
