# Generated by Django 4.2.9 on 2025-04-29 13:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bookoffer_is_active'),
        ('user', '0004_alter_reviews_options_alter_reviews_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-added_at'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-id'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bookoffer', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='description',
            field=models.TextField(blank=True, help_text='Текстовый отзыв (необязательно)', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='grade',
            field=models.IntegerField(blank=True, help_text='Оценка от 0 до 5', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='offer',
            field=models.ForeignKey(help_text='Объявление, на которое оставлен отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.bookoffer', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, оставивший отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='От пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[user.models.validate_birth_date], verbose_name='Дата рождения'),
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('subscribed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Подписан на')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.CheckConstraint(check=models.Q(('subscriber', models.F('subscribed_to')), _negated=True), name='prevent_self_subscription'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together={('subscriber', 'subscribed_to')},
        ),
    ]
